import fs from "fs"
import crypto from "crypto"
import net from "net"
import path from "path"
import { spawnSync } from "child_process"
import { fileURLToPath } from "url"

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, "..")
const envPath = path.join(repoRoot, ".env")
const migrationDir = path.join(repoRoot, "db", "migrations")
const cliArgs = new Set(process.argv.slice(2))
const insecurePasswords = new Set([
  "postgres",
  "password",
  "changeme",
  "change_me_before_deploying",
  "change-me-before-deploying",
  "change_me_before_running",
  "change-me-before-running",
])

const results = []

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {}
  const parsed = {}
  const lines = fs.readFileSync(filePath, "utf8").split(/\r?\n/)

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith("#")) continue
    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (!match) continue

    let value = match[2].trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    parsed[match[1]] = value
  }

  return parsed
}

function escapeEnvValue(value) {
  return /[\s#"]/.test(value) ? `"${value.replace(/"/g, '\\"')}"` : value
}

function createDefaultEnvFile() {
  const allowedBasePath = process.env.SCG_ALLOWED_BASE_PATHS || path.dirname(repoRoot)
  const apiKey = process.env.SCG_API_KEYS || crypto.randomBytes(32).toString("hex")
  const lines = [
    "# ContextZero local configuration generated by npm run doctor -- --fix",
    `DB_HOST=${process.env.DB_HOST || "localhost"}`,
    `DB_PORT=${process.env.DB_PORT || "5432"}`,
    `DB_NAME=${process.env.DB_NAME || "scg_v2"}`,
    `DB_USER=${process.env.DB_USER || "postgres"}`,
    `DB_PASSWORD=${escapeEnvValue(process.env.DB_PASSWORD || "CHANGE_ME_BEFORE_RUNNING")}`,
    `NODE_ENV=${process.env.NODE_ENV || "development"}`,
    `LOG_LEVEL=${process.env.LOG_LEVEL || "info"}`,
    `SCG_API_KEYS=${escapeEnvValue(apiKey)}`,
    `SCG_ALLOWED_BASE_PATHS=${escapeEnvValue(allowedBasePath)}`,
    `SCG_MAX_FILES_PER_REPO=${process.env.SCG_MAX_FILES_PER_REPO || "20000"}`,
    `SCG_MAX_FILE_SIZE_BYTES=${process.env.SCG_MAX_FILE_SIZE_BYTES || "1048576"}`,
    `SCG_INGEST_WORKERS=${process.env.SCG_INGEST_WORKERS || "4"}`,
    `SCG_PYTHON_TIMEOUT_MS=${process.env.SCG_PYTHON_TIMEOUT_MS || "30000"}`,
    "",
  ]
  fs.writeFileSync(envPath, lines.join("\n"), "utf8")
}

if (cliArgs.has("--fix") && !fs.existsSync(envPath)) {
  createDefaultEnvFile()
}

const fileEnv = parseEnvFile(envPath)
const env = { ...fileEnv, ...process.env }

function pass(name, detail = "") {
  results.push({ status: "PASS", name, detail })
}

function warn(name, detail = "") {
  results.push({ status: "WARN", name, detail })
}

function fail(name, detail = "") {
  results.push({ status: "FAIL", name, detail })
}

function commandName(name) {
  return process.platform === "win32" ? `${name}.cmd` : name
}

function run(command, args, options = {}) {
  return spawnSync(command, args, {
    cwd: repoRoot,
    env: { ...fileEnv, ...process.env },
    encoding: "utf8",
    timeout: options.timeout ?? 15000,
    windowsHide: true,
  })
}

function checkNode() {
  const major = Number(process.versions.node.split(".")[0])
  if (major >= 20) {
    pass("Node.js version", process.version)
  } else {
    fail("Node.js version", `found ${process.version}; ContextZero requires Node.js 20+`)
  }
}

function checkFiles() {
  if (fs.existsSync(envPath)) {
    pass(".env file", envPath)
  } else {
    warn(".env file", "missing; run npm run setup or copy .env.example to .env")
  }

  const packageLock = path.join(repoRoot, "package-lock.json")
  if (fs.existsSync(packageLock)) {
    pass("package-lock.json", "present")
  } else {
    warn("package-lock.json", "missing; reproducible installs are weaker without it")
  }

  const nodeModules = path.join(repoRoot, "node_modules")
  if (fs.existsSync(nodeModules)) {
    pass("node_modules", "dependencies installed")
  } else {
    fail("node_modules", "missing; run npm install")
  }

  const bridge = path.join(repoRoot, "dist", "mcp-bridge", "index.js")
  if (fs.existsSync(bridge)) {
    pass("MCP bridge build", bridge)
  } else {
    fail("MCP bridge build", "missing dist/mcp-bridge/index.js; run npm run build")
  }

  const pythonExtractor = path.join(repoRoot, "dist", "adapters", "py", "extractor.py")
  if (fs.existsSync(pythonExtractor)) {
    pass("Python adapter build artifact", pythonExtractor)
  } else {
    fail("Python adapter build artifact", "missing dist/adapters/py/extractor.py; run npm run build")
  }
}

function checkEnv() {
  const nodeEnv = (env.NODE_ENV || "development").toLowerCase()
  const allowed = (env.SCG_ALLOWED_BASE_PATHS || "")
    .split(",")
    .map((v) => v.trim())
    .filter(Boolean)

  if (nodeEnv === "production") {
    const password = env.DB_PASSWORD || env.PGPASSWORD || ""
    const normalizedPassword = password.trim().toLowerCase()
    if (!password || insecurePasswords.has(normalizedPassword)) {
      fail("Production database password", "DB_PASSWORD/PGPASSWORD must be set to a strong value")
    } else {
      pass("Production database password", "set")
    }

    const apiKeys = (env.SCG_API_KEYS || "")
      .split(",")
      .map((v) => v.trim())
      .filter(Boolean)
    if (apiKeys.length === 0 || apiKeys.some((v) => v.length < 32 || v === "your-secret-key-here")) {
      warn("REST API keys", "set strong SCG_API_KEYS before exposing the HTTP server")
    } else {
      pass("REST API keys", `${apiKeys.length} key(s) configured`)
    }

    const dbHost = env.DB_HOST || env.PGHOST || "localhost"
    const sslMode = (env.DB_SSL_MODE || "disable").toLowerCase()
    const allowPrivateNetwork = ["1", "true", "yes", "on"].includes(
      (env.DB_SSL_ALLOW_INSECURE_PRIVATE_NETWORK || "").trim().toLowerCase(),
    )
    const localHosts = new Set(["localhost", "127.0.0.1", "::1"])
    if (sslMode === "disable" && !localHosts.has(dbHost) && !allowPrivateNetwork) {
      fail(
        "Production database SSL",
        "remote DB_HOST requires DB_SSL_MODE=verify-ca/verify-full or explicit DB_SSL_ALLOW_INSECURE_PRIVATE_NETWORK=true",
      )
    } else {
      pass("Production database SSL policy", sslMode === "disable" ? "explicitly local/private" : sslMode)
    }
  } else {
    pass("Runtime mode", nodeEnv)
  }

  if (allowed.length === 0) {
    warn(
      "Allowed repository paths",
      "SCG_ALLOWED_BASE_PATHS is empty; MCP falls back to process cwd, HTTP rejects repo registration",
    )
  } else {
    const missing = allowed.filter((p) => !path.isAbsolute(p) || !fs.existsSync(p))
    if (missing.length > 0) {
      fail("Allowed repository paths", `invalid or missing path(s): ${missing.join(", ")}`)
    } else {
      pass("Allowed repository paths", `${allowed.length} path(s) configured`)
    }
  }

  const maxFiles = env.SCG_MAX_FILES_PER_REPO || "100000"
  const maxFileSize = env.SCG_MAX_FILE_SIZE_BYTES || "1048576"
  const workers = env.SCG_INGEST_WORKERS || "8"
  pass("Ingestion limits", `files=${maxFiles}, file_size_bytes=${maxFileSize}, workers=${workers}`)
}

function checkTreeSitter() {
  const code = `
const { extractWithTreeSitter } = require('./dist/adapters/universal');
const samples = {
  bash: 'function ok() { echo hi; }',
  php: '<?php function ok() { return 1; }',
  swift: 'func ok() -> Int { return 1 }',
  cpp: 'int ok() { return 1; }',
  rust: 'fn ok() -> i32 { 1 }',
  go: 'package main\\nfunc ok() int { return 1 }'
};
for (const [name, source] of Object.entries(samples)) {
  const result = extractWithTreeSitter('doctor.' + name, source, name);
  if (!result || !Array.isArray(result.symbols)) {
    throw new Error('invalid extraction result for ' + name);
  }
}
`
  const result = run(process.execPath, ["-e", code], { timeout: 15000 })
  if (result.status === 0) {
    pass("Tree-sitter grammars", "bash, php, swift, cpp, rust, go loaded")
  } else {
    fail("Tree-sitter grammars", (result.stderr || result.stdout || "grammar load failed").trim())
  }
}

function checkPython() {
  const python = env.PYTHON_BIN || (process.platform === "win32" ? "python" : "python3")
  const result = run(python, ["-c", 'import libcst; print("libcst-ok")'], { timeout: 15000 })
  if (result.status === 0) {
    pass("Python LibCST adapter dependency", python)
  } else {
    fail(
      "Python LibCST adapter dependency",
      `unable to import libcst with ${python}; run: ${python} -m pip install libcst`,
    )
  }
}

async function checkDatabase() {
  const host = env.DB_HOST || env.PGHOST || "localhost"
  const port = Number(env.DB_PORT || env.PGPORT || 5432)

  const reachable = await new Promise((resolve) => {
    const socket = net.createConnection({ host, port })
    const done = (value) => {
      socket.destroy()
      resolve(value)
    }
    socket.setTimeout(5000)
    socket.once("connect", () => done(true))
    socket.once("timeout", () => done(false))
    socket.once("error", () => done(false))
  })

  if (!reachable) {
    fail("PostgreSQL TCP connection", `${host}:${port} is not reachable`)
    return
  }
  pass("PostgreSQL TCP connection", `${host}:${port}`)

  let pg
  try {
    pg = await import("pg")
  } catch {
    fail("PostgreSQL driver", "pg package is unavailable; run npm install")
    return
  }

  const sslMode = (env.DB_SSL_MODE || "disable").toLowerCase()
  let ssl = false
  if (sslMode === "require") ssl = { rejectUnauthorized: false }
  if (sslMode === "verify-ca" || sslMode === "verify-full") {
    ssl = { rejectUnauthorized: true }
    if (env.DB_SSL_CA) {
      ssl.ca = fs.readFileSync(env.DB_SSL_CA, "utf8")
    }
  }

  const configuredPassword = env.DB_PASSWORD ?? env.PGPASSWORD
  const client = new pg.Client({
    host,
    port,
    database: env.DB_NAME || env.PGDATABASE || "scg_v2",
    user: env.DB_USER || env.PGUSER || "postgres",
    password: String(configuredPassword ?? ""),
    connectionTimeoutMillis: 5000,
    ssl,
  })

  try {
    await client.connect()
    const dbInfo = await client.query("SELECT current_database() AS database, current_setting($1) AS version", [
      "server_version",
    ])
    pass("PostgreSQL query", `${dbInfo.rows[0].database} on ${dbInfo.rows[0].version}`)

    const extension = await client.query(
      "SELECT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') AS installed",
    )
    if (extension.rows[0].installed === true) {
      pass("pg_trgm extension", "installed")
    } else {
      fail("pg_trgm extension", "missing; run: CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    }

    const migrations = fs.existsSync(migrationDir)
      ? fs.readdirSync(migrationDir).filter((file) => file.endsWith(".sql")).length
      : 0
    const table = await client.query("SELECT to_regclass('public._migrations') AS table_name")
    if (!table.rows[0].table_name) {
      fail("Database migrations", "not applied; run npm run db:migrate")
    } else {
      const applied = await client.query("SELECT COUNT(*)::int AS count FROM _migrations")
      const count = Number(applied.rows[0].count)
      if (count < migrations) {
        fail("Database migrations", `${count}/${migrations} applied; run npm run db:migrate`)
      } else {
        pass("Database migrations", `${count}/${migrations} applied`)
      }
    }
  } catch (error) {
    let message = error instanceof Error ? error.message : String(error)
    if (!configuredPassword && /password must be a string|SASL/i.test(message)) {
      message = "DB_PASSWORD/PGPASSWORD is not set; set it in .env or in the process environment"
    }
    fail("PostgreSQL query", message)
  } finally {
    await client.end().catch(() => {})
  }
}

function printResults() {
  const failCount = results.filter((item) => item.status === "FAIL").length
  const warnCount = results.filter((item) => item.status === "WARN").length

  if (cliArgs.has("--json")) {
    console.log(
      JSON.stringify(
        {
          status: failCount > 0 ? "fail" : warnCount > 0 ? "warn" : "pass",
          summary: {
            failures: failCount,
            warnings: warnCount,
          },
          results,
        },
        null,
        2,
      ),
    )
    return failCount
  }

  console.log("ContextZero doctor")
  console.log("==================")
  for (const item of results) {
    const suffix = item.detail ? ` - ${item.detail}` : ""
    console.log(`[${item.status}] ${item.name}${suffix}`)
  }

  console.log("")
  console.log(`Summary: ${failCount} failure(s), ${warnCount} warning(s)`)
  return failCount
}

checkNode()
checkFiles()
checkEnv()
checkTreeSitter()
checkPython()
await checkDatabase()

const failures = printResults()
process.exit(failures > 0 ? 1 : 0)
